sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product ittn-008
env:
  global:
    -
      # LTD_AWS_ID
      secure: akWv6kq2ig6gJYU9bN+PY88V12k/gAE/M1Q5UhthL2inlCg26eR/HSvL4cFxeEof07f6JmeUTW44ewLGTimJUC2ZmJMGXDLu/Y4XtyZNqAOK4N2XnjpcZ9BZcRVj4gvqWiu6xCwWJQ6vvGkowm8CRgWyJ8goSbSfJ4zGe4FXd05KxxCpeFtVVj3GvkwH6zVhYuIddN70VLEYRf5Q5zjFDNwiutxQohfHt9bWGhT/rvAXlVaLn6KLnJ8tf0KDXaSuekpb5ZAlNkLYIN5m9uRc5XwLpadHSuCaOYf1YnIf9y3wq6mAcL4b6ZsleQjILjscUq00VjSxujX0OOp3Awp6DwXHCwf/BCutKo/54MjSd/V2A/Fb5muHeeAua7lQehIbAxluD+Najf30nxq0EcX3qkB7EEyT0u3dqWYHnn4YL8T1FiJoyuhclkTq7EwU8pZFGoksQ2mOzrPrEjGi+ibitrMAwBZPU602mrkkMsrcGSXs+AdgAiqVlXFczT75iFDsfOywu7amptN43X3U/4/oCp8JKaI3is0zq0AsmFwax+9HY/Kp5vpIdB7DQuY2GLnW0olSc06U/KF5TCBFlAI6KkgQDgnRfjixEAOQDhWAseOe8jmH318EWdytsziHdncuctWS9w8OUcVRBc6mEPi7Y35VV1fQ9lyIMxEs/FOVeCA=
    -
      # LTD_AWS_SECRET
      secure: cAAPbhJnytKoNUaNbM4atz1eSFDJ/zWtqEC6LfTpL9/MLScVMKYQvRbkb7X5J3PFoZ2vV1If5F5hCjVqIeycJhmz4LhvSSMTa8CLUSYQZ9NZoQw2sAY54ZkIANqHb/CzQ8YIA/cV4O8XONmA93N/gZ01vZK+xBpTwKZXyorhhPpJ4zK2dv0aLjgshXUrTbrfq8td0h8OgxTpXfFP+7Kykm2frskHaxBLsFJlyWOGzy9qcO/Jcigj9p0aYBuMbrFjriV5sfEuhhtMLsP++bwnqH/buxnthYWQ3tS9XiulVqRCawNgLmT7iXGbWwuK4RMXOQ6KVPNgwdAqaDXVJBJgS9ReexJCJ4TQhq9dROUMA/HzgVfRKVafgVXRLc102TZoKK344wU1lbU2iC8y2dqZdTQiJi4FP+K9hcTt3XAKD2nJPIv+qwtHJ9qGMMlEDwX2scA+ZZ7OuVmc+vjHI46APxz67+0s4RD/AJWtxq6FMLToaj9JHE2aErSRdEWb/O2drwXgSYrgWW2N9Y8YBEPhXeBlPjFxOPlHlHBotdDY838f91JjpQmZtWZgxXVAibzApDG9Hj4g5jl5pCATCAh/omSBd1VitYoYC6AXd6E97KZp/XPtbnCM4uYx1OBUa38rzGTWUI8K6F2uDSKNk3zmq5MJnUq8z68NI5rhbgUdXZk=
    -
      # LTD_USERNAME
      secure: kWENhZ7RtZooeDcfCMaWn3rv6rwb/JbxbR2ky6bFKSY6X7Wfosy/ANmzg6VIaRrkFbv4fPV/qDzd+ETzh1wcoyagdPNYQwhoT5C8TIjmYGHCUgFH69GlTRrrUM4LgRamDOG8lJv8toXjURYf3/EJP5EBXG8LKMILa/oXfbKqMQ7P5u9G3WBvNAdZlIwARvhr3QLbHl05WlsCHTjdzYm0SeU8L6yNuM734YUKMkZj5c9+Pewpg53ZfJqMgXrT0dN1eltup1VUvz6K+6LopNAZ0pZTL85xTpnCgtg01QUui9ZEQjq9zPiVC5rSJ8+m0tA5cLArD3eCd/r0Bj7N1aZB6JD3K0+YTqyvs/7YLQHBkoDUZjqLfvsFCFOfr0REiGRid5c4KOLWkcPclkyx0f9LMhSSUU8z5v4MQsmWk+tK9EEcEIxIar0UeG2Ai58MMpBxSBaRsqP2Twv5YWKimklaKjMJ4cmCzUom29rPeuc1EzCHmbyMEJ7SQV0yexaiV+VG1JSVXMpQ+E+9AnnN1vGlzTdj25+o7JjI80t0ee0R2AOa5OXldwF5i5v/SLgCFghxeba0mJ8PWZurD1XlFkA0TYKLFfV+WnfC1ZP37Ys41rsnymfuLbnPxiLM+r3Yl9rr/gkU5VCy1I/RT2mjhdS7ywXUk7PaSg80dG4ZmDwozak=
    -
      # LTD_PASSWORD
      secure: njw77KMZuLu2DJx3Jsfzhu1rpi68r9CBwimhrwlwO0E3eTfqBDfrvQEmRnV45r2ToI9qUVmi23Mea+LnQhFQULUXxMcNB7aRPIVmwYZyms0RQS893wrVg5LDDOenfXAGtizNAt7lmy+HOZwHMxiHvhYFCyyQtZNkMnBYEO/KxI210t2BLLmoEsLODhI+xWuV6KvuEzT+sLi1Aw7hDfdp9rl51LMKUEtUIUsHSuixcxBIi2QQotgSb5HVyMKJzJFWLk3yx4R0eDtLP51EQUBfkbP5YoLaljrq42mIrhApa6/yljCCGBhJzpyOqulzuaBNqPkRtnA2qMjF4joFOK9Yf4DuZ/14+x7DQozQVsroCjNhcowtN9T0ab8xzE4ulT22BYXbOSm8QsuwulVYCcdWHyUAC8fNhv6rirKXH8DqBN2Kl5cN/IhwFfWBarXoz8y0sD88X0+gTqxYfNCaq8BoBBceO1CCuT0PLTAw+gaalT7KBhkczIPXCWW0ej5EHkOV+d7Gxnn25Zi9zk734cTPKMrj46mTeKJ/9SISxlQFiyG4AI8nz2FvrVC40pwvMq2Dlfo1hQP6HypGWCOAWONnVI4KM7m6iQF8SCCXkVXeDyCAH2pPAoTCy0l5re/3T7zuhwZi/mItyjnUcgxJQM7uIG0CfA2hQHGrdfOENsXRO7E=
